version: '2'

services:
  pmm-data:
    build: .
    image: percona/pmm-server
    container_name: pmm-data
    volumes:
      - /var/lib/mysql
      - /opt/prometheus/data
      - /opt/consul-data
    entrypoint: /bin/true

  pmm-server:
    build: .
    container_name: pmm-server
    image: percona/pmm-server
    ports:
      - "80:80"
    volumes_from:
      - pmm-data
#    environment:
#      - METRICS_RETENTION=720h
#      - METRICS_MEMORY=262144
